export const CONNECT = 'CONNECT';
export const CONNECTED = 'CONNECTED';
export const CONNECTING = 'CONNECTING';
export const DISCONNECT = 'DISCONNECT';
export const DISCONNECTED = 'DISCONNECTED';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const FETCH_HN_REQUEST = 'FETCH_HN_REQUEST';
export const FETCH_HN_SUCCESS = 'FETCH_HN_SUCCESS';
export const FETCH_HN_FAILURE = 'FETCH_HN_FAILURE';

export const FETCH_STOCK_REQUEST = 'FETCH_STOCK_REQUEST';
export const FETCH_STOCK_SUCCESS = 'FETCH_STOCK_SUCCESS';
export const FETCH_STOCK_FAILURE = 'FETCH_STOCK_FAILURE';

export const FETCH_PERSON_NAME_REQUEST = 'FETCH_PERSON_NAME_REQUEST'
export const FETCH_PERSON_NAME_SUCCESS = 'FETCH_PERSON_NAME_SUCCESS'
export const FETCH_PERSON_NAME_FAILURE = 'FETCH_PERSON_NAME_FAILURE'
export const UPDATE_TRAINING = "UPDATE_TRAINING"


